name: Build & Upload Plugin Zip

on:
  release:
    types: [published]

jobs:
  build-zip:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Create plugin zip with correct folder name
        run: |
          mkdir -p package
          rsync -av --exclude=.git --exclude=.github --exclude=package ./ package/dvly-bricks-elements
          cd package
          zip -r dvly-bricks-elements.zip dvly-bricks-elements

      - name: Upload release asset
        uses: softprops/action-gh-release@v1
        with:
          files: package/dvly-bricks-elements.zip
          token: ${{ secrets.GH_PAT }}
